######################################################################
# Automatically generated by qmake (3.0) Fri Feb 26 13:01:02 2016
######################################################################

TEMPLATE = app
TARGET = qt_button_tutorial
INCLUDEPATH += .


QT += widgets \
		gui

# Input
SOURCES += qt_button_tutorial.cpp
